### ISSUE TITLE
PSR-0 tree

### ISSUE THREAD

**Issue by remicollet** [sebastianbergmann/php-file-iterator#26]
Wouldn't be better to keep Facade.php and Factory.php under a "Iterator" directory ?

At least it will make simpler for downstream distribution to recreate the previous PSR-0 compliant tree (even if we still provide, and mostly rely on the classmap autoloader ).

**Comment by vtsao** [comment]
Agreed, the current directory structure of the files doesn't match their pseudo-namespacing.
