### ISSUE TITLE
Error File_Iterator_Facade not found ?

### ISSUE THREAD

**Issue by Chrysweel** [sebastianbergmann/php-file-iterator#33]
I just update my composer and It update 

>  - Removing phpunit/php-file-iterator (dev-master 3cc8f69)
> - Installing phpunit/php-file-iterator (dev-master 930e4df)

Now I get the following error:
```
PHP Fatal error:  Uncaught Error: Class 'File_Iterator_Facade' not found in /var/www/html/vendor/phpunit/phpunit/src/Util/Configuration.php:926
Stack trace:
#0 /var/www/html/vendor/phpunit/phpunit/src/Util/Configuration.php(868): PHPUnit_Util_Configuration->getTestSuite(Object(DOMElement), NULL)
#1 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(783): PHPUnit_Util_Configuration->getTestSuiteConfiguration(NULL)
#2 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(129): PHPUnit_TextUI_Command->handleArguments(Array)
#3 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(118): PHPUnit_TextUI_Command->run(Array, true)
#4 /var/www/html/vendor/phpunit/phpunit/phpunit(52): PHPUnit_TextUI_Command::main()
#5 {main}
  thrown in /var/www/html/vendor/phpunit/phpunit/src/Util/Configuration.php on line 926
```

Any idea ?

**Comment by sebastianbergmann** [comment]
* PHPUnit has not been updated yet with regard to recent changes in `master` of this component
* `master` of this component is `2.0.x-dev`
* PHPUnit (including its `master`) depends on `^1.4.2` of this comonent
* If you are force-installing `master` of this component (or similar) then you are on your own

**Comment by Chrysweel** [comment]
Ok @sebastianbergmann thanks! I force version 1.4.2 of php-file-iterator. 
Thanks !
