### ISSUE TITLE
Regression causes "No tests executed!"

### ISSUE THREAD

**Issue by kylekatarnls** [sebastianbergmann/php-file-iterator#37]
Hi, I tried the exact same build with php-file-iterator 1.4.3:
https://travis-ci.org/pug-php/pug-symfony/jobs/307889898
Execute all tests.

And with 1.4.4:
https://travis-ci.org/pug-php/pug-symfony/jobs/307872780
Output `No tests executed!`

Something with the new exclude system seems too restrictive.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by kylekatarnls** [comment]
But I don't know the root cause, I use PHPUnit and find the breaking change on php-file-iterator by testing all dependencies that changed meanwhile.

But the diff between 1.4.3 and 1.4.4 is pretty short and I think we can find the problem in few steps.

First can you show me where you unit-test you methods, like the one introduced by 1.4.4: `isExcludeParentOrSame`?

**Comment by sebastianbergmann** [comment]
The fix for #30 was reverted in 730b01bc3e867237eaac355e06a36b85dd93a8b4 and version 1.4.5 has been tagged.

**Comment by kylekatarnls** [comment]
Thanks for the revert, I will try help you to reproduce.
