### ISSUE TITLE
Regression in 2.0 causes File_Iterator to filter everything if target has hidden parent directory

### ISSUE THREAD

**Issue by soerenbernstein** [sebastianbergmann/php-file-iterator#46]
I've just updated PHPUnit to 7.2.4 and our TeamCity CI-Server is not running any tests anymore. The reason imho that the TeamCity agents are using hidden work directories. So it seem, we're back to square #1.

**Comment by sebastianbergmann** [comment]
Thank you for your report.

Please provide a **minimal**, **self-contained**, reproducing test case that shows the problem you are reporting.

Without such a minimal, self-contained, reproducing test case I will not be able to investigate this issue.

**Comment by soerenbernstein** [comment]
Reapplying 84aedf6 with a tweaking is restoring functionality, but I'm not sure, if this is still the desired solution. The problem is that the preg_match in Iterator::accept is testing the whole path, when it should only test the path below the "project" directory.

Concerning the minimal, self-contained test case I'm not quite sure how to provide it. Basically, you can use any project which is working with PHPUnit 7.2 and rename a parent folder outside the project folder to ".<whatever>".

**Comment by sebastianbergmann** [comment]
@slavcodev @kamazee @j-d Could you guys have a look, please, whether this regression is caused by your changes? Thanks!

**Comment by slavcodev** [comment]
@sebastianbergmann @soerenbernstein There is proposal of the fix.

**Comment by soerenbernstein** [comment]
Tested the proposed fix and it works for me.
