### ISSUE TITLE
Excluding a non-existing file from a suite causes the entire suite being skipped

### ISSUE THREAD

**Issue by morozov** [sebastianbergmann/php-file-iterator#55]
This issue is reproducible with PHPUnit 7.3.5 installed via composer.

Sample configuration file:
```xml
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
>
    <testsuites>
        <testsuite name="PHPUnit">
            <directory>tests</directory>
            <exclude>tests/NonExistingFile.php</exclude>
        </testsuite>
    </testsuites>
</phpunit>
```
Given that the `tests/` directory is not empty and contains valid tests, running `phpunit` produces:
```
$ phpunit 
PHPUnit 7.3.5 by Sebastian Bergmann and contributors.

Time: 12 ms, Memory: 2.00MB

No tests executed!
```
Removing the `<exclude>` fixes the issue:
```
$ phpunit 
PHPUnit 7.3.5 by Sebastian Bergmann and contributors.

.                                                                                   1 / 1 (100%)

Time: 20 ms, Memory: 4.00MB

OK (1 test, 1 assertion)
```

The issue seems to be introduced by https://github.com/sebastianbergmann/php-file-iterator/pull/35 which added `realpath()` filtering for excluded paths. For a non-existing path, `Factory::getPathsAfterResolvingWildcards()` returns `false` which later are interpreted somewhere in PHPUnit as current directory:
```php
$path = '/non/existing/file';
var_dump($path);

$path = realpath($path);
var_dump($path);

$path = realpath($path);
var_dump($path);

// string(18) "/non/existing/file"
// bool(false)
// string(21) "/home/morozov"
```

**Comment by sebastianbergmann** [comment]
I am almost sure this was fixed by @thomasweinert and @localheinz during last week's code sprint. Can you test with current `master` of php-file-iterator?

**Comment by sebastianbergmann** [comment]
Thanks. I'll have to roll a release then :-)
