### ISSUE TITLE
tools/composer should be export-ignored

### ISSUE THREAD

**Issue by garak** [sebastianbergmann/php-file-iterator#65]
I just upgraded phpunit in one of my projects, and found an annoying warning about LoggerInterface being defined twice.
It looks like the culprit is `tools/composer` file in this library, that was not present with phpunit 8.5 while it is with phpunit 9.0

I think that such file should be added to `.gitattributes` with an `export-ignore` flag.
I can provide a PR.

**Comment by sebastianbergmann** [comment]
[`.gitattributes`](https://raw.githubusercontent.com/sebastianbergmann/php-file-iterator/master/.gitattributes) already has this:

```
/tools      export-ignore
/tools/*    binary

*.php diff=php
```

**Comment by garak** [comment]
I guess it's only a matter of releases then.
Thanks for the response!
