### ISSUE TITLE
File missing while using `File_Iterator_Factory`

### ISSUE THREAD

**Issue by nlrex** [sebastianbergmann/php-file-iterator#68]
As my test files increasing, I found some of the test case was not able to run. I got the message like this:

```
Time: 1.7 seconds, Memory: 6.00MB

No tests executed!

Process finished with exit code 0
```

After running some tests, I figure out that the problem occurs at `/src/Facade.php::getFilesAsArray`.  

When using `foreach` to run the iterartor created by `File_Iterator_Factory`, it seems to be ok in normal situation. But when the files in the directory up to more than 60, some of the files seems to be missing. 

It may be a problem with php's iterator, And I suggest that you can call `$iterator->rewind()` before using `foreach`. Or you can use `$iterator->next()` and other funtions to iterate.

You can use the file below to reproduce the problem of `RecursiveDirectoryIterator`, which is used in `File_Iterator_Factory`
[reproduce_test_code.txt](https://github.com/sebastianbergmann/php-file-iterator/files/5173725/reproduce_test_code.txt)

**Comment by sebastianbergmann** [comment]
I ran your script, this is the result I get:

```
get by foreach: 65
get by foreach with rewind: 65
get by foreach after foreach: 65
get by loop: 65
get by iterator_to_array: 65
get by iterator_to_array with rewind: 65
```

This looks correct to me? Which version of PHP do you use?

**Comment by sebastianbergmann** [comment]
Looking at https://3v4l.org/d0OJs, I would assume that you are using PHP 7.4.8.

**Comment by nlrex** [comment]
I have tried PHP 7.2.33 and PHP 7.4.10, both output the result like this:

```
[docker://php:7.4-fpm-alpine/]:php /opt/project/Test.php
get by foreach: 1
get by foreach with rewind: 65
get by foreach after foreach: 65
get by loop: 65
get by iterator_to_array: 1
get by iterator_to_array with rewind: 65

Process finished with exit code 0
```

Futther more, I run in the docker container. I don't know whether it have any affect or not.

**Comment by nlrex** [comment]
I have tried increasing the amount of  file up to 200 and the result comes more weird:

```
[docker://php:7.4-fpm-alpine/]:php /opt/project/Test.php
get by foreach: 138
get by foreach with rewind: 74
get by foreach after foreach: 202
get by loop: 202
get by iterator_to_array: 138
get by iterator_to_array with rewind: 74

Process finished with exit code 0
```

**Comment by sebastianbergmann** [comment]
I am closing this as I do not believe this to be a bug in this library. If at all, this would have to be a bug in PHP.

**Comment by theseer** [comment]
For the record: Even when PHP is run in podman (aka docker done right ;-p) it works:

```
$ podman run -it --rm -v .:/tmp:Z -w /tmp docker.io/phpdaily/php:8.0.0-dev-cli-alpine3.10 php test.php
get by foreach: 65
get by foreach with rewind: 65
get by foreach after foreach: 65
get by loop: 65
get by iterator_to_array: 65
get by iterator_to_array with rewind: 65
```

This must be something very specific to your environment.

**Comment by nlrex** [comment]
Thanks a lot for reviewing this issue! I should try some other tests to find out the reason.

**Comment by nlrex** [comment]
@sebastianbergmann @theseer 
Hi there, I finally find out that the reason to problem is actually the environment!!!
I was using the docker with the `WSL 2 based engine` under the Windows system. As soon as I changed the docker engine into `Legacy Hyper-V backend`, the problem disappeared.

Thanks again
