### ISSUE TITLE
Add type information to SebastianBergmann\FileIterator\Iterator

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/php-file-iterator#77]
[Psalm](https://github.com/sebastianbergmann/php-file-iterator/actions/runs/4044049796/jobs/6953725357#step:5:1) currently reports:

```
INFO: MissingTemplateParam - src/Iterator.php:27:13 - SebastianBergmann\FileIterator\Iterator
has missing template params when extending FilterIterator, expecting 3 (see https://psalm.dev/182)
final class Iterator extends FilterIterator
```

However, I do not (yet) know how to use `@template-extends` to document the fact that `SebastianBergmann\FileIterator\Iterator` extends `\FilterIterator` to iterate over `\AppendIterator(\RecursiveIteratorIterator(\RecursiveDirectoryIterator))` and returns a `string` for each iteration step.

**Comment by mvriel** [comment]
I don't have the opportunity to check this out right now, but would this help?

```
/**
 * @template TKey as array-key
 * @template T as SplFileInfo
 * @template TIterator as Iterator<TKey, T>
 *
 * @extends FilterIterator<TKey, T, TIterator>
 */
class Iterator extends FilterIterator {
```

IIRC, this will define the Iterator as a FilterIterator that has an (inner) Iterator of SplFileInfo objects and a regular array-key as its key

**Comment by mvriel** [comment]
Reading your comment above, I am wondering whether what I provided works. I based the types on the source code where I saw an assertion on SplFileInfo

**Comment by sebastianbergmann** [comment]
Thank you for your comment, Mike, but I do not think that this will work. And I realize that my use case (an outer iterator that also maps from one type (`SplFileInfo`) to another type (`string`) is ... at least an edge case ;-)

**Comment by muglug** [comment]
Would you want something like

```
@extends FilterIterator<int, string, AppendIterator>
```
?

**Comment by sebastianbergmann** [comment]
@muglug May I bother you again? The recently introduced `SebastianBergmann\FileIterator\ExcludeIterator` needs some template love:

```
ERROR: MissingTemplateParam - src/ExcludeIterator.php:21:13 - SebastianBergmann\FileIterator\ExcludeIterator has missing template params when extending RecursiveFilterIterator, expecting 3 (see https://psalm.dev/182)
final class ExcludeIterator extends RecursiveFilterIterator
```

**Comment by muglug** [comment]
What keys and values do you get out of iterating over it? And what does `getInnerIterator()` return? Those are the three template params you need to provide

**Comment by sebastianbergmann** [comment]
`getInnerIterator()` returns `RecursiveDirectoryIterator` and we are iterating over `SplFileInfo` objects.

When I use
```php
/**
 * @template-extends RecursiveFilterIterator<int, SplFileInfo, RecursiveIterator<int, SplFileInfo>>
 */
final class ExcludeIterator extends RecursiveFilterIterator
```
then I get
```
ERROR: InvalidArgument - src/ExcludeIterator.php:36:29 - Argument 1 of RecursiveFilterIterator::__construct
expects RecursiveIterator<int, SplFileInfo>, but RecursiveDirectoryIterator provided (see https://psalm.dev/004)
        parent::__construct($iterator);
```
When I then use
```php
    /**
     * @psalm-param RecursiveIterator<int, SplFileInfo> $iterator
     * @psalm-param list<string> $exclude
     */
    public function __construct(RecursiveDirectoryIterator $iterator, array $exclude)
```
then I get
```
ERROR: MismatchingDocblockParamType - src/ExcludeIterator.php:32:21 - Parameter $iterator has wrong type
'RecursiveIterator<int, SplFileInfo>', should be 'RecursiveDirectoryIterator' (see https://psalm.dev/141)
     * @psalm-param RecursiveIterator<int, SplFileInfo> $iterator


ERROR: InvalidArgument - src/ExcludeIterator.php:67:13 - Argument 1 of
SebastianBergmann\FileIterator\ExcludeIterator::__construct expects RecursiveIterator<int, SplFileInfo>,
but RecursiveDirectoryIterator provided (see https://psalm.dev/004)
            $this->getInnerIterator()->getChildren(),
```
