### ISSUE TITLE
Accept `array|string $paths` in `Facade::getFilesAsArray()`

### ISSUE THREAD

**Issue by mkrauser** [sebastianbergmann/php-file-iterator#81]
Hey Sebastian, 

first of all, thank you for your amazing work you've done for the community!

I wondered, if theres a reason why the Facade::getFilesAsArray(...) only accepts a single path as string? 

https://github.com/sebastianbergmann/php-file-iterator/blob/main/src/Facade.php#L29

The Factory::getFileIterator(...) can already handle an array of directories, so this would be only a minor change.
I'll be happy to provide a PR for this, if that's OK with you.

/Matthias

**Comment by sebastianbergmann** [comment]
Thank you for your patience, I totally forgot about this.
